
# This is your Supabase project configuration

project_id = "acboajrjgqqnfrtozssb"

[api]
# Port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns in a single request. Defaults to 1000.
# To disable the limit use .limit(null)
# max_rows = 1000

[db]
# Port = 54322
# The database major version to use. This must be the same as your remote database's
# major version.
major_version = 15

[studio]
# Port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored and accessible from the Inbucket app.
[inbucket]
# Port = 54324
# smtp_port = 54325
# pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A comma separated list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
# jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If disabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure analytics storage to be the local pganalytics instance
backend = "postgres"
database_url = "postgres://postgres:postgres@localhost:54322/postgres"

# Function and Edge functions settings
[functions]
# Port = 54321
database_url = "postgresql://postgres:postgres@host.internal:5432/postgres"

[functions.detect-eq-breakthrough]
# Defines the JWT verification mode for the function
verify_jwt = true

[functions.chat-completion]
verify_jwt = true
