
project_id = "acboajrjgqqnfrtozssb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[db.migrations.directories]]
path = "supabase/migrations"

[functions]
[functions.admin-get-user-emails]
verify_jwt = true
